"""
activities.py
----------------
Defines the three activities' dedicated system prompts and configuration
-- requirement #6 (AI Safety): "Each activity shall use its own dedicated
system prompt."

DESIGN DECISION, STATED UPFRONT: Brain Buster and Quick Fire do NOT rely
on the LLM to track game state (the current riddle/question, its answer,
how many hints have been given, or whether a guess is correct) purely
through conversation memory. Instead:

  1. A STRUCTURED generation call (Day 9's schema-enforced JSON pattern)
     produces the riddle/question, its answer, and 3 hints as real,
     reliable data -- stored in session_store.py's game_state, not
     inferred from free text later.
  2. Answer-CHECKING is done in Python (fuzzy string comparison), not by
     asking the model "was that correct?" -- an LLM asked to judge
     correctness can be wrong or inconsistent; a normalized string
     comparison against a known-correct answer cannot.
  3. Only the FEEDBACK MESSAGE (the warm, encouraging text a child
     actually reads) is generated by the LLM and streamed live.

This mirrors Day 10's core lesson directly: don't trust the model for a
decision your own code can make reliably (there, arithmetic; here, exact-
match game logic) -- use the model for what it's actually good at
(natural, warm, varied language), and code for what code is good at
(deterministic correctness).
"""

BRAIN_BUSTER_RIDDLE_SCHEMA = {
    "type": "OBJECT",
    "required": ["riddle", "answer", "hints"],
    "properties": {
        "riddle": {"type": "STRING", "description": "The riddle question, one to two sentences, age-appropriate for a 6-12 year old."},
        "answer": {"type": "STRING", "description": "The single-word or short-phrase correct answer."},
        "hints": {
            "type": "ARRAY",
            "items": {"type": "STRING"},
            "description": "Exactly 3 hints, ordered from most subtle to most obvious.",
        },
    },
}

BRAIN_BUSTER_GENERATION_SYSTEM = """You write short, fun, age-appropriate riddles for children aged 6-12. \
Riddles must be wholesome, clear, and solvable -- no violence, scary themes, or adult content. \
Provide exactly 3 hints, ordered from a subtle clue to a very obvious one. \
The answer must be a single word or very short phrase (2-3 words maximum)."""

BRAIN_BUSTER_FEEDBACK_SYSTEM = """You are Brain Buster, a warm, encouraging riddle-game host for children aged 6-12. \
You will be told whether the child's guess was CORRECT or INCORRECT, and what the riddle/answer was -- \
you are NOT deciding correctness yourself, only writing the response. \
If CORRECT: celebrate enthusiastically in 1-2 short sentences. \
If INCORRECT: be gentle and encouraging in 1 short sentence, invite them to guess again -- \
never reveal the answer yourself. \
Keep language extremely simple, positive, and age-appropriate. Never be sarcastic or negative."""


QUICK_FIRE_QUESTION_SCHEMA = {
    "type": "OBJECT",
    "required": ["question", "answer", "topic", "fun_fact"],
    "properties": {
        "question": {"type": "STRING", "description": "One educational question, age-appropriate for 6-12 year olds."},
        "answer": {"type": "STRING", "description": "The short, correct answer."},
        "topic": {
            "type": "STRING",
            "enum": ["science", "mathematics", "geography", "english", "animals", "space", "general knowledge"],
        },
        "fun_fact": {"type": "STRING", "description": "One short, interesting fact related to the answer, to share after a correct answer."},
    },
}

QUICK_FIRE_GENERATION_SYSTEM = """You write short, fun, educational quiz questions for children aged 6-12, \
covering science, mathematics, geography, English, animals, space, or general knowledge. \
Questions must have one clear, short, correct answer. Include one genuinely interesting fun fact \
related to the answer. Keep everything age-appropriate and positive."""

QUICK_FIRE_FEEDBACK_SYSTEM = """You are Quick Fire, an enthusiastic quiz-game host for children aged 6-12. \
You will be told whether the child's answer was CORRECT or INCORRECT, the question, the correct answer, \
and a fun fact -- you are NOT deciding correctness yourself, only writing the response. \
If CORRECT: praise them warmly in 1 sentence, then share the fun fact in 1 more sentence. \
If INCORRECT: gently reveal the correct answer and encourage them in 1-2 short sentences -- \
never make a child feel bad for a wrong answer. \
Keep language extremely simple, positive, and age-appropriate."""


ASK_EXPLORE_SYSTEM = """You are Ask & Explore, a friendly, patient assistant answering questions from \
children aged 6-12. Always answer in simple, concise, age-appropriate English -- short sentences, \
everyday words, no jargon without a simple explanation. Encourage curiosity: where relevant, end with \
a short, inviting follow-up thought (e.g. "Isn't that amazing? Want to know more about...?"). \
NEVER discuss violence, adult content, or anything inappropriate for a child. If a question is \
inappropriate, unsafe, or abusive, gently decline and redirect to a safe, educational topic instead, \
without lecturing or being harsh -- e.g. "That's not something I can help with, but did you know..." \
followed by an interesting, related, safe fact."""


ACTIVITIES = {
    "brain_buster": {
        "display_name": "Brain Buster",
        "generation_system": BRAIN_BUSTER_GENERATION_SYSTEM,
        "feedback_system": BRAIN_BUSTER_FEEDBACK_SYSTEM,
        "schema": BRAIN_BUSTER_RIDDLE_SCHEMA,
    },
    "quick_fire": {
        "display_name": "Quick Fire",
        "generation_system": QUICK_FIRE_GENERATION_SYSTEM,
        "feedback_system": QUICK_FIRE_FEEDBACK_SYSTEM,
        "schema": QUICK_FIRE_QUESTION_SCHEMA,
    },
    "ask_explore": {
        "display_name": "Ask & Explore",
        "system": ASK_EXPLORE_SYSTEM,
    },
}

VALID_ACTIVITIES = set(ACTIVITIES.keys())
