"""
build_final_json.py
-----------------------
Stage 4 of the Day 7 mini-project: combine everything into a single JSON
file containing the query, each retrieval method's top result and score,
and both LLM answers (temperature 0.1 and 0.9), exactly as the task spec
requires.
"""

import json


def main():
    with open("outputs/retrieval_results.json", encoding="utf-8") as f:
        retrieval = json.load(f)

    from llm_answer_generation import call_claude_simulation, QUERY

    context = retrieval["final_retrieved_context"]
    answer_low = json.loads(call_claude_simulation(QUERY, context, temperature=0.1))
    answer_high = json.loads(call_claude_simulation(QUERY, context, temperature=0.9))

    final_output = {
        "query": retrieval["query"],
        "retrieval_comparison": retrieval["retrieval_comparison"],
        "final_retrieved_context": retrieval["final_retrieved_context"],
        "llm_answers": {
            "temperature_0.1": answer_low,
            "temperature_0.9": answer_high,
        },
        "methodology_note": (
            "Embedding retrieval (Method 3) used averaged Word2Vec trained on this "
            "corpus, substituting for all-MiniLM-L6-v2 since this verification "
            "environment cannot reach huggingface.co. LLM answers were generated by "
            "Claude reasoning through the structured prompt twice under low/high- "
            "temperature framings, substituting for the Gemini API since this "
            "environment cannot reach generativelanguage.googleapis.com. Fully correct "
            "reference code for both (sentence_transformer_local.py, the "
            "call_gemini_api() function in llm_answer_generation.py) is provided for "
            "local execution with real internet access and API keys."
        ),
    }

    with open("outputs/final_output.json", "w", encoding="utf-8") as f:
        json.dump(final_output, f, indent=2)

    print("Final combined JSON saved to outputs/final_output.json")
    print(json.dumps(final_output, indent=2))


if __name__ == "__main__":
    main()
